### PR TITLE
Added Truer representation of the Dark Soda / Monokai theme

### PR DESCRIPTION
**Pull request by adambullmer**
Additional Theme: Dark Soda / Monokai

### CODE REVIEW

**Comment by s10wen** [comment]
Could you add some screenshots please? No worries, if not, I'll take a look when I can.

**Comment by s10wen** [comment]
@adambullmer nice job on this dude! It's getting there, but it I noticed a few things:

screen shot 2015-02-05 at 19 34 45
screen shot 2015-02-05 at 19 34 52
screen shot 2015-02-05 at 19 35 48

Personally I prefer the original with the darker background so there's more contrast, but I'm happy to add it in as another theme when the above issues are fixed if you or anyone else want to use it.

**Comment by mauricecruz** [comment]
:+1: Nice theme!

I think those style issues are not theme specific. I have them in mine too. Guess we should log that as an issue and I'll tackle it on the next update.

**Comment by s10wen** [comment]
@mauricecruz ahh, all good in my theme :star: Hmmmmmeee :stuck_out_tongue_winking_eye:

**Comment by adambullmer** [comment]
Yeah, as I kept going through the tabs, I've found some more areas that need some work, or just a moment of attention. If you want to put this on hold for now, I can probably update it tonight

**Comment by s10wen** [comment]
Cool, no rush! If you could set it up as another theme as well that would be great, or let me know when you're done and I can sort that.

**Comment by adambullmer** [comment]
@s10wen Looks like there was just a missing style for the network panel if CodeMirror can't parse it. Seems to be minified files that are affected. This should fix it
screen shot 2015-02-05 at 10 06 11 pm

**Comment by s10wen** [comment]
@adambullmer nice work Adam, merged! :star2:

**Comment by mauricecruz** [comment]
:clap: :clap: :clap:

**Pull request merged**
